import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Giovanni',
      email: 'giovani@webpontual.com.br',
      password: bcrypt.hashSync('WebPontu@lGio123'),
      isAdmin: true,
    },
    {
      name: 'Jean',
      email: 'jean@webpontual.com.br',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Placa mãe 1155',
      slug: 'placa-mãe',
      category: 'Placa-mãe',
      image: '/images/fontenb1.jpg',
      price: 399,
      brand: 'MSI',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Modelo Intel socket 1155',
    },
    {
      name: 'Fonte Notebook',
      slug: 'fonte-notebook',
      category: 'Fontes',
      image: '/images/fontenb1.jpg',
      price: 199,
      brand: 'Pontual',
      rating: 4.9,
      numReviews: 18,
      countInStock: 200,
      description: 'Fonte Notebook compatível com Asus, HP, Acer',
    },
    {
      name: 'Fonte Notebook',
      slug: 'fonte-notebook2',
      category: 'Fontes',
      image: '/images/fontenb1.jpg',
      price: 199,
      brand: 'Pontual',
      rating: 4.9,
      numReviews: 18,
      countInStock: 200,
      description: 'Fonte Notebook compatível com Asus, HP, Acer',
    },
    {
      name: 'Fonte Notebook',
      slug: 'fonte-notebook3',
      category: 'Fontes',
      image: '/images/fontenb1.jpg',
      price: 199,
      brand: 'Pontual',
      rating: 4.9,
      numReviews: 18,
      countInStock: 200,
      description: 'Fonte Notebook compatível com Asus, HP, Acer',
    },
    {
      name: 'Fonte Notebook',
      slug: 'fonte-notebook4',
      category: 'Fontes',
      image: '/images/fontenb1.jpg',
      price: 199,
      brand: 'Pontual',
      rating: 4.9,
      numReviews: 18,
      countInStock: 200,
      description: 'Fonte Notebook compatível com Asus, HP, Acer',
    },
    {
      name: 'Fonte Notebook',
      slug: 'fonte-notebook5',
      category: 'Fontes',
      image: '/images/fontenb1.jpg',
      price: 199,
      brand: 'Pontual',
      rating: 4.9,
      numReviews: 18,
      countInStock: 200,
      description: 'Fonte Notebook compatível com Asus, HP, Acer',
    },
  ],
};

export default data;
